server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_db
    username: course_admin
    password: course_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: course
        format_sql: true
